baseURL = "https://carolinasoares.dev/"
defaultContentLanguage = "pt"
enableRobotsTXT = true
languageCode = "pt"
theme = "gokarna"
title = "Carolina Soares"

[menu]
  [[menu.main]]
    name = "Início"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Postagens"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2
  
  [[menu.main]]
    name = "Projetos"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3
  
  [[menu.main]]
    name = "Palestras"
    pre = "<span data-feather='mic'></span>"
    url = "/talks/"
    weight = 4
  
  [[menu.main]]
    name = "Tutoriais"
    pre = "<span data-feather='book-open'></span>"
    url = "/tutorials/"
    weight = 5

  [[menu.main]]
    name = "Marcadores"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 6

  [[menu.main]]
    name = "CV"
    pre = "<span data-feather='briefcase'></span>"
    url = "https://www.canva.com/design/DAGeGLv54jE/7Qcd8GnokhEMtCSflFZG8A/view?utm_content=DAGeGLv54jE&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=h031ce24a37"
    weight = 7
  
  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/mariacarolinass"
    weight = 8
  
  [[menu.main]]
    identifier = "linkedin"
    pre = "<span data-feather='linkedin'></span>"
    url = "https://www.linkedin.com/in/carolinasoaresm/"
    weight = 9
  
  [[menu.main]]
    identifier = "email"
    pre = "<span data-feather='mail'></span>"
    url = "mailto:mcarolinasoares0@gmail.com"
    weight = 11

  [[menu.main]]
    identifier = "buymeacoffee"
    pre = "<span data-feather='coffee'></span>"
    url = "https://www.buymeacoffee.com/mcarolinasz"
    weight = 11

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 12

[params]
  accentColor = "#FF4D4D"

  avatarURL = "/images/avatar.jpg"
  avatarAltText = "avatar"
  avatarSize = "size-m"

  ShowBackToTopButton = true 
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """

  socialIcons = [
    {name = "github", url = "https://github.com/mariacarolinass"},
    {name = "gitlab", url = "https://gitlab.com/mariacarolinass"},
    {name = "linkedin", url = "https://www.linkedin.com/in/carolinasoaresm/"},
    {name = "youtube", url = "https://www.youtube.com/@carolinasoaresdev"},
    {name = "flickr", url = "https://flic.kr/ps/45PSit"},
    {name = "instagram", url = "https://www.instagram.com/carolsoares.m"},
    {name = "bluesky", url = "https://bsky.app/profile/carolinasoaresm.bsky.social"},
    {name = "mastodon", url = "https://mastodon.social/@carolinasoares"},
    {name = "email", url = "mailto:mcarolinasoares0@gmail.com"}
  ]

  dateFormat = "January 2, 2006"
  
  description = "Dev · Entusiasta do conhecimento aberto e software livre · Mantenedora do dadoslivres.org · Embaixadora de Inovação Cívica (OKBR) · Graduando Ciências e Tecnologia com ênfase em Computação Aplicada (UFRN)"

  footer = "Carolina Soares"

  metaKeywords = ["blog", "portfólio", "Carolina Soares", "dev"]

  numberPostsOnHomePage = 4

  showBackToTopButton = true

  showPostsOnHomePage = "popular"

  togglePreviousAndNextButtons = "false"
